### ISSUE TITLE
no "andWhen" method support

### ISSUE THREAD

**Issue by jymail** [duyluonglc/adonis-lucid-mongodb#15]
Hi,

First, thank you for the great job you've done !

In _Adonis v3.2.1_, the API authentication provided by the official _adonis-auth_ module does not work when using the _adonis-lucid-mongodb_ module. It seems that there is several reasons and one of them is the "andWhere" method that is not implemented.

**Comment by duyluonglc** [comment]
@jymail thank for your feedback
there is no `andWhen` method do you mean `andWhere`? 
I'm using with `adonis-auth` without problem.
can you show the error log?

**Comment by jymail** [comment]
@duyluonglc you are right, it's "andWhere".

In fact, there's no error message, but when I debug the code in `adonis-auth` module (more precisely in "adonis-auth/src/Serializers/Lucid/index.js", in the `findByToken()` method), the `andWhere()` method called in it, is `undefined`.

In addition to this, I don't know if the `andWhere()` method does the same as `where()`, but if I implement it in your module (more precilely in "adonis-lucid-mongodb/src/LucidMongo/QueryBuilder/methods.js" as a short-cut to the `where()` method), it seems there is another problem too...

**Comment by jymail** [comment]
**where() / andWhere()** : If we look inside the `knex` module (at "knex/lib/query/builder.js", line 1139), the `andWhere()` method is a shortcut to the `where()` method of `Builder`.

**Comment by duyluonglc** [comment]
@jymail added in 0.45.0, please check

**Comment by jymail** [comment]
@duyluonglc  thank you for the addition of the `andWhere()` method.

Like I told you before, it seems that there is another problem when I try to implement the AdonisJS API authentication. Please, could you try to build an API authentication with adonis-lucid-mongodb ?

**Comment by duyluonglc** [comment]
I only use jwt before
I'll try with api key auth this weekend to see what's problem

**Comment by jymail** [comment]
@duyluonglc thank you

**Comment by duyluonglc** [comment]
@jymail I update new version. Please check the api token auth

**Comment by jymail** [comment]
@duyluonglc  It works !!
Thank you very much !
